params = {
          'savefig.dpi'         : 300,
          'savefig.extension'   : 'auto',
          'figure.figsize'      : (9, 5),
          'figure.dpi'          : 80,
          'figure.facecolor'    : 'white',
          'figure.edgecolor'    : 'white',
          'xtick.major.pad'     : 4,
          'xtick.minor.pad'     : 4,
          'xtick.labelsize'     : 'medium',
          'xtick.direction'     : 'out',
          'xtick.minor.size'    : 0.0,
          'ytick.major.size'    : 4,
          'ytick.minor.size'    : 2,
          'ytick.major.pad'     : 4,
          'ytick.minor.pad'     : 4,
          'ytick.labelsize'     : 'medium',
          'ytick.direction'     : 'out',
          'ytick.minor.size'    : 0.0,
          'axes.linewidth'      : 1.0,
          'axes.grid'           : True,
          'grid.color'          : 'lightgrey',
          'grid.linestyle'      : '-',
          'grid.linewidth'      : 0.5,
          'axes.labelweight'    : 'bold',
          'legend.numpoints'    : 1,
          'legend.fontsize'     : 10,
          'legend.markerscale'  : 1.,
          'legend.labelspacing' : -0.5,
          'legend.handlelength' : 2.,
          'legend.handleheight' : 0.0,
         }
all_defaults = {
'font':{'family':'Times New Roman',
        'weight':'bold',
        'size':10,
       },
'color': 'black',
'markersize': 6,
'markerfacecolor': 'None',
'markeredgewidth': 0.75,
'markeredgecolor': 'black',
'linestyle_marker' : [
                '-',
              ],
'linestyle' : [
                '-',
                '--',
                ':',
                '-.',
              ],
#
'linewidth' : [
                '0.5', # 03

              ],
'marker': [
            '',
            'o',
            '^',
            '>',
            '<',
            'v',
            '+',
            'x',
            'd',
            'D',
            's',
            '1',
            '2',
            '3',
            '4',
          ] ,
}
